# Generated by Django 6.0.4 on 2026-04-18 02:00

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0006_alter_branch_managers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntakeForm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('entity_type', models.CharField(choices=[('lead', 'Lead'), ('member', 'Member'), ('generic', 'Generic')], default='member', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.tenant')),
            ],
            options={
                'db_table': 'intake_forms',
                'ordering': ['name'],
            },
            managers=[
                ('base_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='FormResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('entity_type', models.CharField(choices=[('lead', 'Lead'), ('member', 'Member'), ('generic', 'Generic')], max_length=20)),
                ('entity_id', models.UUIDField(help_text='UUID of the lead or member this response belongs to')),
                ('data', models.JSONField(default=dict)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intake_responses', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.tenant')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='intake.intakeform')),
            ],
            options={
                'db_table': 'intake_form_responses',
            },
            managers=[
                ('base_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('label', models.CharField(max_length=255)),
                ('field_key', models.CharField(help_text='Snake_case identifier. Matches prefill map keys (name, phone, email, age, etc.)', max_length=100)),
                ('field_type', models.CharField(choices=[('text', 'Short Text'), ('textarea', 'Long Text'), ('number', 'Number'), ('date', 'Date'), ('select', 'Dropdown'), ('multiselect', 'Multi-Select'), ('radio', 'Radio Buttons'), ('boolean', 'Yes / No'), ('scale', 'Rating Scale')], max_length=20)),
                ('placeholder', models.CharField(blank=True, max_length=255)),
                ('help_text', models.CharField(blank=True, max_length=500)),
                ('is_required', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('options', models.JSONField(blank=True, default=list)),
                ('scale_config', models.JSONField(blank=True, default=dict)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='intake.intakeform')),
            ],
            options={
                'db_table': 'intake_form_fields',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='intakeform',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='unique_intake_form_name_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='formresponse',
            constraint=models.UniqueConstraint(fields=('form', 'entity_id'), name='unique_form_response_per_entity'),
        ),
    ]
