# Generated by Django 6.0.4 on 2026-04-18 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intakeform',
            name='is_active',
        ),
        migrations.AddField(
            model_name='intakeform',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='intakeform',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('inactive', 'Inactive')], db_index=True, default='draft', max_length=10),
        ),
    ]
