# Generated by Django 6.0.2 on 2026-03-20 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platform_sessions', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
