# Generated by Django 6.0.4 on 2026-05-06 16:23

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0006_alter_branch_managers'),
        ('members', '0004_alter_member_branches'),
        ('verticals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('activity_type', models.CharField(choices=[('ENROLLMENT', 'Enrollment'), ('PAYMENT', 'Payment'), ('DOCUMENT', 'Document'), ('SERVICE_EVENT', 'Service Event'), ('NOTE', 'Note')], db_index=True, max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('reference_type', models.CharField(blank=True, choices=[('membership', 'Membership'), ('booking', 'Booking'), ('class_session', 'Class Session'), ('consultation', 'Consultation'), ('therapy_session', 'Therapy Session'), ('enrollment', 'Enrollment'), ('document', 'Document'), ('other', 'Other')], max_length=50)),
                ('reference_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_activities', to=settings.AUTH_USER_MODEL)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='members.member')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.tenant')),
                ('vertical', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='verticals.businessvertical')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['person', '-created_at'], name='activity_ac_person__a29923_idx'), models.Index(fields=['tenant', 'activity_type'], name='activity_ac_tenant__3747b8_idx')],
            },
            managers=[
                ('base_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
