# Generated by Django 6.0.4 on 2026-05-06 16:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
        ('core', '0006_alter_branch_managers'),
        ('members', '0004_alter_member_branches'),
        ('verticals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['tenant', 'person', '-created_at'], name='activity_ac_tenant__768da4_idx'),
        ),
    ]
