# Generated by Django 6.0.4 on 2026-05-06 16:23

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_initial'),
        ('core', '0006_alter_branch_managers'),
        ('members', '0004_alter_member_branches'),
        ('verticals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='active', max_length=20)),
                ('source_type', models.CharField(blank=True, choices=[('membership', 'Membership'), ('booking', 'Booking'), ('class_session', 'Class Session'), ('consultation', 'Consultation'), ('therapy_session', 'Therapy Session'), ('enrollment', 'Enrollment'), ('document', 'Document'), ('other', 'Other')], max_length=50)),
                ('source_id', models.UUIDField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_enrollments', to=settings.AUTH_USER_MODEL)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='members.member')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='catalog.service')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.tenant')),
                ('vertical', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='verticals.businessvertical')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['person', 'status'], name='enrollments_person__20d06b_idx'), models.Index(fields=['tenant', 'vertical', 'status'], name='enrollments_tenant__3b1cc3_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'active'), ('service__isnull', False)), fields=('tenant', 'person', 'service'), name='unique_active_enrollment_per_person_service')],
            },
            managers=[
                ('base_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
