# Generated by Django 6.0.2 on 2026-03-09 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_managers'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('authority', '0002_role_is_deleted_rolepermission_is_deleted'),
        ('core', '0005_branch_is_deleted_tenant_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_platform_admin',
            field=models.BooleanField(default=False, help_text='Indicates platform-level administrator.'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='users_email_4b85f2_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['tenant'], name='users_tenant__d262cd_idx'),
        ),
    ]
