# Generated by Django 6.0.4 on 2026-05-05 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payouts', '0001_initial'),
        ('verticals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payout',
            name='vertical',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payouts', to='verticals.businessvertical'),
        ),
        migrations.AddIndex(
            model_name='payout',
            index=models.Index(fields=['tenant', 'staff'], name='payouts_pay_tenant__3ee8a4_idx'),
        ),
        migrations.AddIndex(
            model_name='payout',
            index=models.Index(fields=['tenant', 'status'], name='payouts_pay_tenant__690542_idx'),
        ),
    ]
