# Generated by Django 6.0.4 on 2026-04-18 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='communicationlog',
            name='event_type',
            field=models.CharField(blank=True, help_text='System event that triggered this message.', max_length=100),
        ),
    ]
