# Generated by Django 6.0.4 on 2026-04-18 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0002_communicationlog_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='communicationlog',
            name='last_attempt_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='communicationlog',
            name='retry_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
