# Generated by Django 6.0.4 on 2026-04-19 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0004_backoff_priority_dedupe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communicationlog',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped')], default='PENDING', max_length=20),
        ),
    ]
