# Generated by Django 6.0.4 on 2026-07-30 12:08

import apps.payments.utils.encryption
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0005_add_skipped_status'),
        ('core', '0007_tenant_is_platform_tenant_only_one_platform_tenant'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantMessagingConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('provider', models.CharField(choices=[('msg91', 'MSG91 (SMS, India)'), ('whatsapp_cloud', 'Meta WhatsApp Cloud API')], max_length=30)),
                ('api_key', apps.payments.utils.encryption.EncryptedCharField(blank=True, help_text='MSG91 auth key, or Meta WhatsApp access token.')),
                ('sender_id', models.CharField(blank=True, help_text='MSG91 sender/header ID, or Meta WhatsApp phone number ID.', max_length=100)),
                ('template_id', models.CharField(blank=True, help_text='MSG91 DLT template ID, or the approved Meta template name.', max_length=200)),
                ('template_lang', models.CharField(blank=True, help_text='Meta template language code (e.g. en, en_US). Unused for MSG91.', max_length=20)),
                ('is_active', models.BooleanField(default=False, help_text="Off until the tenant's own registration/verification completes.")),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messaging_configs', to='core.tenant')),
            ],
            options={
                'db_table': 'tenant_messaging_configs',
                'unique_together': {('tenant', 'provider')},
            },
        ),
    ]
