# Generated by Django 6.0.2 on 2026-02-22 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='branch',
            name='unique_branch_name_per_tenant',
        ),
        migrations.AlterModelTable(
            name='branch',
            table='members',
        ),
    ]
