# Generated by Django 6.0.2 on 2026-02-22 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_branch_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'ordering': ['name']},
        ),
        migrations.AddConstraint(
            model_name='branch',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='unique_branch_name_per_tenant'),
        ),
        migrations.AlterModelTable(
            name='branch',
            table='branches',
        ),
    ]
