# Generated by Django 6.0.2 on 2026-02-25 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_branch_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='grace_days',
            field=models.PositiveIntegerField(default=0, help_text='Number of grace days after membership final end date'),
        ),
    ]
