# Generated by Django 6.0.2 on 2026-03-10 10:56

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_branch_is_deleted_tenant_is_deleted'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='branch',
            managers=[
                ('base_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
