# Generated by Django 6.0.4 on 2026-07-27 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_branch_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='is_platform',
            field=models.BooleanField(default=False, help_text='Marks the internal ANJASI tenant used for platform-level communication (onboarding, invoices, service notices). It has no members and must be excluded from tenant-facing batch jobs.'),
        ),
        migrations.AddConstraint(
            model_name='tenant',
            constraint=models.UniqueConstraint(condition=models.Q(('is_platform', True)), fields=('is_platform',), name='only_one_platform_tenant'),
        ),
    ]
