# Generated by Django 6.0.4 on 2026-06-28 16:03

import django.core.validators
import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_certificatetemplate'),
        ('core', '0006_alter_branch_managers'),
        ('members', '0004_alter_member_branches'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='assessment',
            managers=[
                ('base_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='assessmentattempt',
            managers=[
                ('base_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='assessmentscore',
            managers=[
                ('base_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='attemptanswer',
            managers=[
                ('base_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='certificatetemplate',
            managers=[
                ('base_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='question',
            managers=[
                ('base_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='questionoption',
            managers=[
                ('base_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='studentassessment',
            managers=[
                ('base_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RenameIndex(
            model_name='certificatetemplate',
            new_name='certificate_tenant__e3543c_idx',
            old_name='assessments_tenant_assessment_idx',
        ),
        migrations.RenameIndex(
            model_name='certificatetemplate',
            new_name='certificate_tenant__886e20_idx',
            old_name='assessments_tenant_is_act_idx',
        ),
        migrations.AddField(
            model_name='assessmentattempt',
            name='questions',
            field=models.ManyToManyField(related_name='attempts', through='assessments.AttemptAnswer', to='assessments.question'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=60, help_text='Time limit in minutes (5 min to 8 hours)', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(480)]),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='easy_percentage',
            field=models.PositiveIntegerField(default=30, help_text='Percentage of easy questions (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='hard_percentage',
            field=models.PositiveIntegerField(default=30, help_text='Percentage of hard questions (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='medium_percentage',
            field=models.PositiveIntegerField(default=40, help_text='Percentage of medium questions (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='passing_score',
            field=models.DecimalField(decimal_places=2, default=60, help_text='Minimum score (%) to pass (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='total_questions',
            field=models.PositiveIntegerField(default=50, help_text='Total number of questions in this exam', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(500)]),
        ),
        migrations.AlterField(
            model_name='assessmentscore',
            name='percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Score as percentage (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='attemptanswer',
            name='selected_option',
            field=models.ForeignKey(blank=True, help_text='The option the student selected', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attempt_answers', to='assessments.questionoption'),
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['tenant', 'status'], name='assessments_tenant__413a81_idx'),
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['tenant', 'is_active'], name='assessments_tenant__bc71e5_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentattempt',
            index=models.Index(fields=['student_assessment', 'status'], name='assessment__student_e18146_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentscore',
            index=models.Index(fields=['student_assessment', 'is_passed'], name='assessment__student_335138_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentscore',
            index=models.Index(fields=['attempt'], name='assessment__attempt_a13fc2_idx'),
        ),
        migrations.AddIndex(
            model_name='attemptanswer',
            index=models.Index(fields=['attempt', 'question'], name='attempt_ans_attempt_91b708_idx'),
        ),
        migrations.AddIndex(
            model_name='attemptanswer',
            index=models.Index(fields=['attempt', 'is_correct'], name='attempt_ans_attempt_cc4e4f_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['assessment', 'difficulty'], name='questions_assessm_302a85_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['assessment', 'status'], name='questions_assessm_8b5377_idx'),
        ),
        migrations.AddIndex(
            model_name='questionoption',
            index=models.Index(fields=['question', 'is_correct'], name='question_op_questio_284133_idx'),
        ),
        migrations.AddIndex(
            model_name='studentassessment',
            index=models.Index(fields=['student', 'assessment'], name='student_ass_student_193518_idx'),
        ),
        migrations.AddIndex(
            model_name='studentassessment',
            index=models.Index(fields=['student', 'status'], name='student_ass_student_3421b8_idx'),
        ),
        migrations.AddIndex(
            model_name='studentassessment',
            index=models.Index(fields=['assessment', 'status'], name='student_ass_assessm_3e08ad_idx'),
        ),
    ]
