# Generated by Django 6.0.4 on 2026-05-05 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_initial'),
        ('core', '0006_alter_branch_managers'),
        ('documents', '0001_initial'),
        ('payments', '0009_payment_vertical_alter_payment_purpose_and_more'),
        ('verticals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='vertical',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='verticals.businessvertical'),
        ),
        migrations.AddField(
            model_name='documentlineitem',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='documents.document'),
        ),
        migrations.AddField(
            model_name='documentlineitem',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='line_items', to='catalog.service'),
        ),
        migrations.AddField(
            model_name='documentsequence',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant'),
        ),
        migrations.AddField(
            model_name='paymentdocumentlink',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_links', to='documents.document'),
        ),
        migrations.AddField(
            model_name='paymentdocumentlink',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_links', to='payments.payment'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['tenant', 'document_type', 'status'], name='documents_d_tenant__3b35a2_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['tenant', 'person'], name='documents_d_tenant__ff11f0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='document',
            unique_together={('tenant', 'document_type', 'document_number')},
        ),
        migrations.AlterUniqueTogether(
            name='documentsequence',
            unique_together={('tenant', 'document_type', 'year')},
        ),
        migrations.AlterUniqueTogether(
            name='paymentdocumentlink',
            unique_together={('payment', 'document')},
        ),
    ]
