# Generated by Django 6.0.4 on 2026-07-30 12:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0007_tenant_is_platform_tenant_only_one_platform_tenant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantInvite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('studio_name', models.CharField(help_text='Becomes the Tenant name.', max_length=255)),
                ('subdomain', models.SlugField(help_text='Becomes the Tenant subdomain. Must still be free at accept time.', max_length=100)),
                ('email', models.EmailField(help_text="Invitee's address. Becomes the Owner user's login.", max_length=254)),
                ('owner_name', models.CharField(blank=True, help_text='Used to address the invite email.', max_length=255)),
                ('token_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REVOKED', 'Revoked')], default='PENDING', max_length=20)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('email_sent', models.BooleanField(default=False)),
                ('email_error', models.TextField(blank=True)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_tenant_invites', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invites', to='core.tenant')),
            ],
            options={
                'db_table': 'tenant_invites',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'expires_at'], name='tenant_invi_status_9354e3_idx'), models.Index(fields=['email'], name='tenant_invi_email_2dd7c9_idx')],
            },
        ),
    ]
