# Generated by Django 6.0.4 on 2026-04-19 11:57

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0006_alter_branch_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantVocabulary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('key', models.CharField(db_index=True, max_length=60)),
                ('label', models.CharField(max_length=120)),
                ('plural_label', models.CharField(blank=True, max_length=120)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocabulary_entries', to='core.tenant')),
            ],
            options={
                'db_table': 'settings_vocabulary',
                'ordering': ['key'],
                'unique_together': {('tenant', 'key')},
            },
            managers=[
                ('base_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
