# Generated by Django 6.0.4 on 2026-04-18 07:13

import apps.payments.utils.encryption
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_branch_managers'),
        ('payments', '0002_replace_payment_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantPaymentConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('provider', models.CharField(default='razorpay', max_length=30)),
                ('key_id', models.CharField(blank=True, max_length=200)),
                ('key_secret', apps.payments.utils.encryption.EncryptedCharField(blank=True)),
                ('webhook_secret', apps.payments.utils.encryption.EncryptedCharField(blank=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'tenant_payment_configs',
            },
        ),
        migrations.RenameIndex(
            model_name='payment',
            new_name='payments_referen_aaa5d3_idx',
            old_name='payments_ref_idx',
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_reference',
            field=models.CharField(blank=True, help_text='UPI txn ID, cheque no., etc.', max_length=200),
        ),
        migrations.AlterField(
            model_name='payment',
            name='reference_type',
            field=models.CharField(blank=True, help_text="e.g. 'membership', 'booking'", max_length=50),
        ),
        migrations.AddField(
            model_name='tenantpaymentconfig',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_configs', to='core.tenant'),
        ),
        migrations.AlterUniqueTogether(
            name='tenantpaymentconfig',
            unique_together={('tenant', 'provider')},
        ),
    ]
