# Generated by Django 6.0.4 on 2026-05-05 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_alter_member_branches'),
        ('payments', '0007_webhook_last_success_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='gst_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='gst_applicable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='gst_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='members.member'),
        ),
    ]
