# Generated by Django 6.0.4 on 2026-05-05 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_payment_gst_amount_payment_gst_applicable_and_more'),
        ('verticals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='vertical',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='verticals.businessvertical'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='purpose',
            field=models.CharField(choices=[('membership', 'Membership'), ('booking', 'Booking'), ('session', 'Session'), ('document', 'Document'), ('other', 'Other')], default='membership', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='reference_type',
            field=models.CharField(blank=True, choices=[('membership', 'Membership'), ('booking', 'Booking'), ('class_session', 'Class Session'), ('consultation', 'Consultation'), ('therapy_session', 'Therapy Session'), ('document', 'Document'), ('other', 'Other')], max_length=50),
        ),
    ]
