# Generated by Django 6.0.2 on 2026-02-25 06:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_branch_options_and_more'),
        ('memberships', '0002_alter_membership_tenant'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('billing_cycle_type', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly'), ('CUSTOM', 'Custom')], max_length=20)),
                ('billing_interval', models.PositiveIntegerField(default=1)),
                ('duration_type', models.CharField(choices=[('FIXED_PERIOD', 'Fixed Period'), ('OPEN_ENDED', 'Open Ended'), ('CUSTOM_DATE_RANGE', 'Custom Date Range')], max_length=30)),
                ('duration_value', models.PositiveIntegerField(blank=True, null=True)),
                ('allow_custom_dates', models.BooleanField(default=False)),
                ('auto_renew_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_plans', to='core.branch')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.tenant')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('tenant', 'branch', 'name')},
            },
        ),
    ]
