# Generated by Django 6.0.2 on 2026-02-25 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0003_membershipplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='memberships.membershipplan'),
        ),
    ]
