# Generated by Django 6.0.2 on 2026-02-25 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0004_membership_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='base_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='discount_type',
            field=models.CharField(choices=[('NONE', 'No Discount'), ('FIXED', 'Fixed Amount'), ('PERCENTAGE', 'Percentage')], default='NONE', max_length=20),
        ),
        migrations.AddField(
            model_name='membership',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
