# Generated by Django 6.0.2 on 2026-02-25 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0006_membershipadjustment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membershipadjustment',
            options={'ordering': ['-created_at']},
        ),
    ]
