# Generated by Django 6.0.2 on 2026-03-08 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0007_alter_membershipadjustment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='membershipadjustment',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
