# Generated by Django 6.0.2 on 2026-03-08 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0008_membership_is_deleted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membershipplan',
            name='duration_type',
        ),
        migrations.RemoveField(
            model_name='membershipplan',
            name='duration_value',
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='class_count',
            field=models.PositiveIntegerField(blank=True, help_text='Used only for CLASS_PACK memberships', null=True),
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='is_template',
            field=models.BooleanField(default=True, help_text='Indicates reusable plan template'),
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='plan_type',
            field=models.CharField(choices=[('DURATION', 'Duration'), ('CLASS_PACK', 'Class Pack'), ('UNLIMITED', 'Unlimited')], default='DURATION', max_length=20),
        ),
    ]
