# Generated by Django 6.0.2 on 2026-03-09 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0009_remove_membershipplan_duration_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='fee_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='membershipplan',
            name='is_template',
            field=models.BooleanField(default=True, help_text='Reusable plan template'),
        ),
    ]
