# Generated by Django 6.0.2 on 2026-03-10 10:56

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0010_alter_membership_fee_amount_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='membership',
            managers=[
                ('base_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='membershipadjustment',
            managers=[
                ('base_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='membershipplan',
            managers=[
                ('base_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
