# Generated by Django 6.0.2 on 2026-03-18 17:37

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_branch_managers'),
        ('memberships', '0011_alter_membership_managers_and_more'),
        ('platform_sessions', '0001_initial'),
        ('attendance', '0001_initial'),  # ✅ IMPORTANT ADD
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipUsage',
            fields=[
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),

                # ✅ FIXED FIELD
                ('attendance', models.ForeignKey(
                    'attendance.attendance',
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='membership_usages'
                )),

                ('membership', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='usages',
                    to='memberships.membership'
                )),

                ('session_instance', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='membership_usages',
                    to='platform_sessions.sessioninstance'
                )),

                ('tenant', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='%(class)ss',
                    to='core.tenant'
                )),
            ],
            options={
                'unique_together': {('membership', 'session_instance')},
            },
            managers=[
                ('base_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]