# Generated by Django 6.0.2 on 2026-02-28 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enquiry',
            options={'verbose_name': 'Enquiry', 'verbose_name_plural': 'Enquiries'},
        ),
        migrations.AlterModelOptions(
            name='enquiryactivity',
            options={'ordering': ['-created_at'], 'verbose_name': 'Enquiry Activity', 'verbose_name_plural': 'Enquiry Activities'},
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='current_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enquiries', to='crm.leadstage'),
        ),
    ]
