# Generated by Django 6.0.2 on 2026-02-28 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_alter_enquiry_created_by'),
        ('members', '0003_remove_member_unique_active_email_per_tenant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='converted_member',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_enquiry', to='members.member'),
        ),
    ]
