# Generated by Django 6.0.2 on 2026-03-05 11:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_tenant_grace_days'),
        ('crm', '0004_alter_enquiry_converted_member'),
        ('members', '0003_remove_member_unique_active_email_per_tenant_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='enquiry',
            constraint=models.UniqueConstraint(fields=('tenant', 'phone'), name='unique_enquiry_phone_per_tenant'),
        ),
    ]
