# Generated by Django 6.0.2 on 2026-03-07 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_enquiry_unique_enquiry_phone_per_tenant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enquiryactivity',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='leadstage',
            name='show_in_pipeline',
            field=models.BooleanField(default=True, help_text='Whether this stage should appear in the Kanban pipeline'),
        ),
        migrations.AddField(
            model_name='leadstage',
            name='stage_type',
            field=models.CharField(choices=[('NEW', 'New'), ('CONTACTED', 'Contacted'), ('DEMO', 'Demo'), ('CONVERTED', 'Converted'), ('LOST', 'Lost'), ('CUSTOM', 'Custom')], default='CUSTOM', max_length=20),
        ),
    ]
