# Generated by Django 6.0.4 on 2026-04-18 13:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_branch_managers'),
        ('crm', '0006_alter_enquiryactivity_options_and_more'),
        ('members', '0004_alter_member_branches'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiryactivity',
            name='action_type',
            field=models.CharField(choices=[('CREATED', 'Created'), ('STAGE_CHANGED', 'Stage Changed'), ('ASSIGNED', 'Assigned'), ('NOTE_ADDED', 'Note Added'), ('CALL_LOGGED', 'Call Logged'), ('CONVERTED', 'Converted'), ('LOST', 'Lost'), ('FOLLOWUP_SCHEDULED', 'Follow-up Scheduled'), ('FOLLOWUP_DONE', 'Follow-up Completed'), ('FOLLOWUP_MISSED', 'Follow-up Missed'), ('MARKED_LOST', 'Marked as Lost')], max_length=50),
        ),
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followup_type', models.CharField(choices=[('call', 'Call'), ('message', 'Message'), ('visit', 'Visit')], default='call', max_length=20)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('done', 'Done'), ('missed', 'Missed')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('reference_type', models.CharField(blank=True, max_length=100)),
                ('reference_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('enquiry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='crm.enquiry')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='members.member')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='core.tenant')),
            ],
            options={
                'db_table': 'crm_followups',
                'ordering': ['due_date', 'status'],
            },
        ),
    ]
