# Generated by Django 6.0.4 on 2026-04-19 12:17

import apps.settings.branding.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0006_alter_branch_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantBranding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='tenant/logos/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='tenant/favicons/')),
                ('primary_color', models.CharField(default='#0d6efd', max_length=7, validators=[apps.settings.branding.models._validate_hex])),
                ('secondary_color', models.CharField(default='#6c757d', max_length=7, validators=[apps.settings.branding.models._validate_hex])),
                ('login_title', models.CharField(blank=True, max_length=100)),
                ('custom_css', models.TextField(blank=True)),
                ('whitelabel_enabled', models.BooleanField(default=False, help_text='Enable white-label branding for this tenant.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='branding', to='core.tenant')),
            ],
            options={
                'db_table': 'settings_branding',
            },
        ),
    ]
