# Generated by Django 6.0.4 on 2026-04-28 02:24

import apps.settings.branding.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_branding', '0002_tenantbranding_custom_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantbranding',
            name='custom_domain',
            field=models.CharField(blank=True, help_text='Tenant custom domain (e.g. app.mygym.com). Used to brand payment and checkout links.', max_length=253, validators=[apps.settings.branding.models._validate_custom_domain]),
        ),
    ]
