# Generated by Django 6.0.4 on 2026-04-15 10:15

import django.db.models.manager
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attendance_type', models.CharField(choices=[('session', 'Session Based'), ('walkin', 'Walk-in'), ('staff', 'Staff'), ('online', 'Online Session')], max_length=20)),
                ('session_date', models.DateField()),
                ('check_in_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('no_show', 'No Show')], default='present', max_length=20)),
                ('session_code', models.CharField(blank=True, max_length=20, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            managers=[
                ('base_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
