# Generated by Django 6.0.2 on 2026-03-19 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('bookings', '0001_initial'),
        ('members', '0004_alter_member_branches'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('member', 'booking', 'session_date')},
        ),
    ]
