# Generated by Django 6.0.2 on 2026-03-20 17:08

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_attendance_unique_together'),
        ('core', '0006_alter_branch_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='attendance',
            managers=[
                ('base_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='attendance',
            name='tenant',
            field=models.ForeignKey(default=uuid.UUID('d5285504-1441-448a-b975-9063af0e04b8'), on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='core.tenant'),
            preserve_default=False,
        ),
    ]
