# Generated by Django 6.0.4 on 2026-05-01 09:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
        ('core', '0006_alter_branch_managers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingsauditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete')], max_length=50),
        ),
        migrations.AlterField(
            model_name='settingsauditlog',
            name='module',
            field=models.CharField(choices=[('payments', 'Payments'), ('memberships', 'Memberships'), ('settings', 'Settings'), ('branding', 'Branding'), ('roles', 'Roles'), ('vocabulary', 'Vocabulary'), ('whatsapp', 'Whatsapp'), ('crm', 'Crm'), ('attendance', 'Attendance'), ('bookings', 'Bookings')], max_length=50),
        ),
        migrations.AddIndex(
            model_name='settingsauditlog',
            index=models.Index(fields=['tenant', 'module', 'action'], name='audit_setti_tenant__f6d094_idx'),
        ),
        migrations.AddIndex(
            model_name='settingsauditlog',
            index=models.Index(fields=['tenant', '-timestamp'], name='audit_setti_tenant__0fd23c_idx'),
        ),
    ]
