# Generated by Django 6.0.4 on 2026-05-01 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_alter_settingsauditlog_action_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingsauditlog',
            name='source',
            field=models.CharField(choices=[('user', 'User'), ('system', 'System')], default='system', max_length=20),
        ),
    ]
