# Generated by Django 6.0.2 on 2026-03-12 09:04

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_branch_managers'),
        ('gym_sessions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionTemplate',
            fields=[
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('duration_minutes', models.PositiveIntegerField()),
                ('capacity', models.PositiveIntegerField(default=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='templates', to='gym_sessions.sessiontype')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.tenant')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('base_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
