# Generated by Django 6.0.2 on 2026-03-12 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym_sessions', '0004_sessioninstance'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sessioninstance',
            unique_together={('schedule', 'session_date', 'start_time')},
        ),
    ]
