# Generated by Django 6.0.2 on 2026-03-12 10:50

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_branch_managers'),
        ('members', '0004_alter_member_branches'),
        ('gym_sessions', '0005_alter_sessioninstance_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('guest_name', models.CharField(blank=True, max_length=255, null=True)),
                ('booking_source', models.CharField(choices=[('member_portal', 'Member Portal'), ('front_desk', 'Front Desk'), ('walk_in', 'Walk In'), ('external_partner', 'External Partner')], default='member_portal', max_length=50)),
                ('external_partner', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('booked', 'Booked'), ('waitlisted', 'Waitlisted'), ('cancelled', 'Cancelled'), ('attended', 'Attended'), ('no_show', 'No Show')], default='booked', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='session_bookings', to='members.member')),
                ('session_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='gym_sessions.sessioninstance')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.tenant')),
            ],
            options={
                'unique_together': {('session_instance', 'member')},
            },
            managers=[
                ('base_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
