# Generated by Django 6.0.2 on 2026-03-12 13:03

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_branch_managers'),
        ('members', '0004_alter_member_branches'),
        ('gym_sessions', '0006_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('guest_name', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent')], default='present', max_length=20)),
                ('attendance_source', models.CharField(choices=[('trainer', 'Trainer'), ('admin', 'Admin / Front Desk'), ('member', 'Member Self Check-In'), ('system', 'System Auto')], default='trainer', max_length=20)),
                ('marked_by', models.UUIDField(blank=True, null=True)),
                ('marked_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.member')),
                ('session_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='gym_sessions.sessioninstance')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.tenant')),
            ],
            options={
                'unique_together': {('session_instance', 'member')},
            },
            managers=[
                ('base_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
