# Generated by Django 6.0.2 on 2026-03-17 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_sessions', '0007_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessiontype',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
