# Generated by Django 6.0.4 on 2026-04-17 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_branch_managers'),
        ('gym_sessions', '0008_sessiontype_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gym_attendances', to='core.tenant'),
        ),
        migrations.AlterField(
            model_name='sessioninstance',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gym_sessioninstances', to='core.tenant'),
        ),
    ]
