# Generated by Django 6.0.2 on 2026-03-10 10:56

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0002_role_is_deleted_rolepermission_is_deleted'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='role',
            managers=[
                ('base_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='rolepermission',
            managers=[
                ('base_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
