# Generated by Django 6.0.2 on 2026-03-11 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0003_alter_role_managers_alter_rolepermission_managers'),
        ('core', '0006_alter_branch_managers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['name']},
        ),
        migrations.AddIndex(
            model_name='permissionaction',
            index=models.Index(fields=['module'], name='permission__module_4591d2_idx'),
        ),
        migrations.AddIndex(
            model_name='rolepermission',
            index=models.Index(fields=['role'], name='role_permis_role_id_0ea48f_idx'),
        ),
    ]
