# Generated by Django 6.0.2 on 2026-02-23 09:36

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_alter_branch_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_members', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='core.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'is_deleted'], name='members_mem_tenant__4327e9_idx'), models.Index(fields=['tenant', 'email'], name='members_mem_tenant__f4b38f_idx'), models.Index(fields=['tenant', 'first_name'], name='members_mem_tenant__36a750_idx'), models.Index(fields=['tenant', 'last_name'], name='members_mem_tenant__a0b1f3_idx')],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('email'), models.F('tenant'), condition=models.Q(('is_deleted', False)), name='unique_active_email_per_tenant')],
            },
        ),
    ]
