# Generated by Django 6.0.2 on 2026-02-23 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_branch_options_and_more'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='branches',
            field=models.ManyToManyField(blank=True, related_name='members', to='core.branch'),
        ),
    ]
