# Generated by Django 6.0.2 on 2026-02-27 12:25

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_tenant_grace_days'),
        ('members', '0002_member_branches'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='member',
            name='unique_active_email_per_tenant',
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddConstraint(
            model_name='member',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), models.F('tenant'), condition=models.Q(('is_deleted', False), ('email__isnull', False)), name='unique_active_email_per_tenant'),
        ),
    ]
