# Generated by Django 6.0.2 on 2026-03-10 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_branch_managers'),
        ('members', '0003_remove_member_unique_active_email_per_tenant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='branches',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_deleted': False}, related_name='members', to='core.branch'),
        ),
    ]
